import Head from "next/head";
import { CartModal } from "components/CartModal/CartModal";
import { Gallery } from "../components/Gallery/Gallery";
import { Header } from "../components/Header/Header";
import styles from "../styles/Home.module.css";
import { dbConnect } from "@lib/dbConnect";
import Product from "@models/Product";
import React, { useState, useEffect } from "react";
import { ProductInfo } from "components/ProductInfo/ProductInfo";
import { ProductContext } from "components/ProductContext/ProductContext";
import { CartPortal } from "components/CartPortal/CartPortal";

export default function Home({ products }) {
  const { onDelete, cartItems, formatPrice, setOpenModal, openModal } = React.useContext(ProductContext)
  const [images, setImages] = useState([]);
  const firstImg = products[0].images[0].full;

  useEffect(() => {
    products.map((product) => {
      const imgs = product.images;
      setImages(imgs);
    });
  }, [products]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/" />
      </Head>
      <Header />

      <CartPortal>
        { !!openModal &&
          <CartModal formatPrice={formatPrice} cartItems={cartItems} onDelete={onDelete} />
        }
      </CartPortal>

      <main className={styles.main}>
        <div className={styles.productContainer}>
          <Gallery images={images} firstImg={firstImg} />
        </div>
        <ProductInfo products={products} />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getServerSideProps() {
  try {
    await dbConnect();
    const res = await Product.find({});

    const products = res.map((item) => {
      const product = item.toObject();
      product._id = `${product._id}`;
      return product;
    });

    return { props: { products } };
  } catch (error) {
    console.log(error);
  }
}
