import Head from "next/head";
import Image from "next/image";
import { Gallery } from "../components/Gallery/Gallery";
import { Header } from "../components/Header/Header";
import styles from "../styles/Home.module.css";
import { dbConnect } from '@lib/dbConnect'
import Product from "@models/Product";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/" />
      </Head>
      <Header />

      <main className={styles.main}>
        <div className={styles.productContainer}>
          <Gallery />
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getServerSideProps() {
  try {
    await dbConnect()
    const res = await Product.find({})
    console.log(res)

    return {props: {product: 123}}
  } catch (error) {
    console.log(error)    
  }
}
